docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "Installation and Requirements": install.md
        - Usage: usage.md
        - Middleware: middleware.md
        - "Error Handlers": error-handlers.md
        - "Creating Middleware": creating-middleware.md
        - "Composing middleware": executing-middleware.md
        - "API Reference": api.md
        - Migration:
          - "To Version 2": migration/to-v2.md
          - "Preparing for Version 3": migration/preparing-for-v3.md
site_name: laminas-stratigility
site_description: laminas-stratigility
repo_url: 'https://github.com/laminas/laminas-stratigility'
