docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "Installation and Requirements": install.md
        - Usage: usage.md
        - Middleware: middleware.md
        - "Error Handlers": error-handlers.md
        - "Creating Middleware": creating-middleware.md
        - "Executing and composing middleware": executing-middleware.md
        - "API Reference": api.md
        - Migration: migration.md
    - v1:
        - "Installation and Requirements": v1/install.md
        - Usage: v1/usage.md
        - Middleware: v1/middleware.md
        - "Error Handlers": v1/error-handlers.md
        - "Creating Middleware": v1/creating-middleware.md
        - "Executing and composing middleware": v1/executing-middleware.md
        - "API Reference": v1/api.md
    - v2:
        - "Installation and Requirements": v2/install.md
        - Usage: v2/usage.md
        - Middleware: v2/middleware.md
        - "Error Handlers": v2/error-handlers.md
        - "Creating Middleware": v2/creating-middleware.md
        - "Executing and composing middleware": v2/executing-middleware.md
        - "API Reference": v2/api.md
        - Migration: v2/migration.md
site_name: laminas-stratigility
site_description: laminas-stratigility
repo_url: 'https://github.com/laminas/laminas-stratigility'
